### ISSUE TITLE
Admin tools not available

### ISSUE THREAD

**Issue by oarchner** [BayCEER/bayeos-viewer-php#8]
Logged in as root on a fresh installation gives me the following warning:
![clipboard03](https://cloud.githubusercontent.com/assets/5363999/8109432/e2811480-1056-11e5-973f-bad0eb88f03f.jpg)

**Comment by holzheu** [comment]
The default database connection in bayeos-viewer.ini was
<pre>
dbname=bayeos user=bayeos
</pre>

This did not work with default pg_hba.conf. Changed to 
<pre>
host=localhost dbname=bayeos user=bayeos password=4336bc9de7a6b11940e897ee22956d51
</pre>
which is the same as for the bayeos-server.

Fix will be included in 1.0.8 release.
